name: Request for translation
description: Request for translation
title: "[TR]: "
labels: ["enhancement", "translation"]
projects: ["bot-wikifolklore", "bot-wikifolklore-issues"]
assignees:
  - nokibsarkar
body:
  - type: markdown
    attributes:
      value: |
        Thanks for requesting a translation! Please fill out the information below to help us get started.
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email, wiki username, telegram username, etc.
    validations:
      required: true
  - type: dropdown
    id: language
    attributes:
      label: Language
      description: What language do you want to translate to?
      options:
        - Afrikaans (af)
        - Albanian (sq)
        - Amharic (am)
        - Arabic (ar)
        - Armenian (hy)
        - Azerbaijani (az)
        - Basque (eu)
        - Belarusian (be)
        - Bengali (bn)
        - Bosnian (bs)
        - Bulgarian (bg)
        - Catalan (ca)
        - Cebuano (ceb)
        - Chichewa (ny)
        - Chinese (Simplified) (zh-CN)
        - Chinese (Traditional) (zh-TW)
        - Corsican (co)
        - Croatian (hr)
        - Czech (cs)
        - Danish (da)
        - Dutch (nl)
        - English (en)
        - Esperanto (eo)
        - Estonian (et)
        - Filipino (tl)
        - Finnish (fi)
        - French (fr)
        - Frisian (fy)
        - Galician (gl)
        - Georgian (ka)
        - German (de)
        - Greek (el)
        - Gujarati (gu)
        - Haitian Creole (ht)
        - Hausa (ha)
        - Hawaiian (haw)
        - Hebrew (he)
        - Hindi (hi)
        - Hmong (hmn)
        - Hungarian (hu)
        - Icelandic (is)
        - Igbo (ig)
        - Indonesian (id)
        - Irish (ga)
        - Italian (it)
        - Japanese (ja)
        - Javanese (jv)
        - Kannada (kn)
        - Kazakh (kk)
        - Khmer (km)
        - Kinyarwanda (rw)
        - Korean (ko)
        - Kurdish (Kurmanji) (ku)
        - Kyrgyz (ky)
        - Lao (lo)
        - Latin (la)
        - Latvian (lv)
        - Lithuanian (lt)
        - Luxembourgish (lb)
        - Macedonian (mk)
        - Malagasy (mg)
        - Malay (ms)
        - Malayalam (ml)
        - Maltese (mt)
        - Maori (mi)
        - Marathi (mr)
        - Mongolian (mn)
        - Myanmar (Burmese) (my)
        - Nepali (ne)
        - Norwegian (no)
        - Odia (Oriya) (or)
        - Pashto (ps)
        - Persian (fa)
        - Polish (pl)
        - Portuguese (pt)
        - Punjabi (pa)
        - Romanian (ro)
        - Russian (ru)
        - Samoan (sm)
        - Scots Gaelic (gd)
        - Serbian (sr)
        - Sesotho (st)
        - Shona (sn)
        - Sindhi (sd)
        - Sinhala (si)
        - Slovak (sk)
        - Slovenian (sl)
        - Somali (so)
        - Spanish (es)
        - Sundanese (su)
        - Swahili (sw)
        - Swedish (sv)
        - Tajik (tg)
        - Tamil (ta)
        - Tatar (tt)
        - Telugu (te)
        - Thai (th)
        - Turkish (tr)
        - Turkmen (tk)
        - Ukrainian (uk)
        - Urdu (ur)
        - Uyghur (ug)
        - Uzbek (uz)
        - Vietnamese (vi)
        - Welsh (cy)
        - Xhosa (xh)
        - Yiddish (yi)
        - Yoruba (yo)
        - Zulu (zu)
    validations:
      required: true
  - type: dropdown
    id: tool
    attributes:
      label: Tool
      description: What tool do you want to translate?
      options:
        - CampWiz
      default: 0
    validations:
      required: true
  - type: checkboxes
    id: file_type
    attributes:
      label: Are you familiar with the JSON file format?
      options:
        - label: I have knowledge about JSON file format
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
